# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
platform :ios do
 

default_platform(:ios)
lane :test do
  scan(
    project: "SimpleCalculator.xcodeproj",
    configuration: "Debug",
    scheme: "SimpleCalculator",
    device: "iPhone 8 Plus",
    sdk: "iphonesimulator",
    output_types: "html"
    )
end

lane :release
   set_github_release
     (
 	    repository_name: "ninaa0718/iOS",
 	    api_token: ENV['github'],
 	    name: ENV['name'],
 	    tag_name: ENV['tag'],
 	    commitish: master,
 	    description: test_results,
      is_draft: false,
      upload_assets: ["./fastlane/test_output"]
 	   )
end
end


