# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
platform :ios do
 

default_platform(:ios)
lane :test
scan(
    xcodeproj: "SimpleCalculator.xcodeproj",
    configuration: "Debug",
    scheme: "SimpleCalculator",
    device: "iPhone 8 Plus",
    sdk: "iphonesimulator",
    output_types: "html"
  )

end
end

